print("Hello GitHub!")

name = input("What is your name? ")
print("Hello", name)
print("This line was added directly on GitHub.")
print("This line was added locally.")
print("This line was added on GitHub again.")
print("This line was added on GitHub again by Aman.")
print("This line was added on GitHub again by Sir pirzada.")
print("This line was added on GitHub again by Sir Ali.")